# Udemy: Vectors 


## Code Challenge : Lecture 14 
#### create 2 4x6 matrices of random numbers 
#### Use a for-loop to compute dot products between corresponding columns. 



In [74]:
import numpy as np 
import math
import matplotlib

In [77]:
a = np.random.randint(10, size=(4,6))
a

array([[0, 6, 3, 0, 4, 2],
       [1, 3, 7, 2, 0, 9],
       [2, 4, 8, 6, 1, 2],
       [2, 8, 3, 7, 9, 6]])

In [84]:
b = np.random.randint(10, size =(4,6))
b

c = np.zeros((4,6))
c

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [85]:
sum_ = 0
for ii,ii_val in enumerate(a):
     c[ii] = a[ii] * b[ii]
        
c



array([[ 0., 42., 18.,  0.,  4., 16.],
       [ 3., 21.,  7., 14.,  0., 45.],
       [10., 24.,  8., 42.,  3.,  4.],
       [18., 56., 12., 49., 27.,  6.]])

## Code Challenge: Lecture 17

#### Test Whether the dot product sign is invariant to scalar multiplication

In [40]:
aa = np.random.randint(10, size = (3,1))
aa
aa = np.transpose(aa)

In [41]:
bb = np.random.randint(10, size = (3,1))
bb
# bb = np.transpose(bb)
# bb


array([[0],
       [8],
       [5]])

In [42]:
ans_ = np.dot(aa,bb)
ans_


array([[28]])

In [48]:
scalar_1 = -3
aa_s = scalar_1 * aa
aa_s

array([[  0,  -3, -12]])

In [53]:
scalar_2 = 2
bb_s = scalar_2 * bb
bb_s

array([[ 0],
       [16],
       [10]])

In [54]:
ans_s_ = np.dot(aa_s,bb_s)
ans_s_


array([[-168]])

## RESULT: 
#### Since we can see changing the scalar values and then multiplying it changes the direction of final vector. Thus Dot product is NOT invariant to Scalar multiplication. 

## Code Challenge: Lecture 18

#### Test Whether the dot product is Commutative

In [66]:
aaa = aa = np.random.randint(10, size = (3,1))
aaa_1 = np.transpose(aaa)
aaa

array([[2],
       [3],
       [7]])

In [67]:
bbb = aa = np.random.randint(10, size = (3,1))
bbb_1 = np.transpose(bbb)
bbb


array([[8],
       [0],
       [3]])

In [68]:
ans1_  = np.dot(aaa_1,bbb)
ans1_

array([[37]])

In [69]:
ans2_ = np.dot(bbb_1,aaa)
ans2_


array([[37]])

In [70]:
print(ans1_ == ans2_)

[[ True]]


## RESULT: 
#### Since aTb = bTa. Thus the Vector dot product is the commutative. It contains Commutative Property./


## Code Challenge: Lecture 19

#### Create two random-integers vectors (R4)
#### Compute the lengths of the individual vectors and magnitude of their dot product 
#### Normalize the Vectors
#### Compute the magnitude of that dot product. 


In [72]:
aaaa = np.random.randint(10, size = (4,1))
aaaa

array([[8],
       [9],
       [5],
       [4]])

In [73]:
bbbb = np.random.randint(10, size = (4,1))
bbbb

array([[4],
       [2],
       [4],
       [3]])

In [76]:
mag_aaaa = np.linalg.norm(aaaa)
mag_aaaa


13.638181696985855

In [77]:
mag_bbbb = np.linalg.norm(bbbb)
mag_bbbb

6.708203932499369

In [80]:
ans_dot1 = np.abs(np.dot(np.transpose(aaaa),bbbb))
ans_dot1

array([[82]])

In [83]:
## Normalizing the vector:

aaaa_norm = aaaa/mag_aaaa
aaaa_norm

array([[0.58658846],
       [0.65991202],
       [0.36661779],
       [0.29329423]])

In [84]:
bbbb_norm = bbbb/mag_bbbb
bbbb_norm

array([[0.59628479],
       [0.2981424 ],
       [0.59628479],
       [0.4472136 ]])

##### To compute the magnitude of their dot product

In [85]:
norm_dot = np.abs(np.dot(np.transpose(aaaa_norm),bbbb_norm))
norm_dot

array([[0.89629531]])

##### To Check its unit vector

In [86]:

aaaa_norm1 = np.linalg.norm(aaaa_norm)
aaaa_norm1


1.0

In [88]:
bbbb_norm1 = np.linalg.norm(bbbb_norm)
bbbb_norm1


1.0